---

 - name: Install apache HTTPD server using Ansible Playbook
   hosts: all
   become: yes

   tasks: 
    - name: update apt package cache
      apt:
        update_cache: yes

    - name: Install apache2 package
      apt: 
        name: apache2
        state: present

    - name: start apache2 service 
      service:
        name: apache2 
        state: started
        enabled: yes
