---

- name: Install to start  nginx on target server
  hosts: all
  become: yes
  gather_facts: yes  #include
  
  tasks:  
   - name: update apt
     apt: 
       update_cache: yes
  
   - name: Install nginx
     apt: 
       name: nginx
       state: present

   - name: start nginx
     service:
        name: nginx
        state: started
        enabled: yes
 

   - name: wait for 60 sec and then stop ngnix
     command: systemctl stop nginx
     async: 60
     poll: 0

   - name: stop nginx
     service: 
        name: nginx
        state: stopped
              
      
